Repository fine-ants/demolition, pull requests merged in 2024-03, with the labels that each got.

#7 [feature] Add retryFn util function
  dist/utils/index.d.ts
  dist/utils/index.js
  dist/utils/retryFn/retryFn.d.ts
  dist/utils/retryFn/retryFn.js
  dist/utils/retryFn/retryFn.test.d.ts
  dist/utils/retryFn/retryFn.test.js
  packages/utils/index.ts
  packages/utils/retryFn/retryFn.test.ts
  packages/utils/retryFn/retryFn.ts
Labels: feature

#6 [feature] Add getElapsedSince function
  dist/utils/date/getElapsedSince/getElapsedSince.d.ts
  dist/utils/date/getElapsedSince/getElapsedSince.js
  dist/utils/date/getElapsedSince/getElapsedSince.test.d.ts
  dist/utils/date/getElapsedSince/getElapsedSince.test.js
  dist/utils/date/getElapsedSince/index.d.ts
  dist/utils/date/getElapsedSince/index.js
  dist/utils/date/index.d.ts
  dist/utils/date/index.js
  dist/utils/index.d.ts
  dist/utils/index.js
  package-lock.json
  packages/utils/date/getElapsedSince/getElapsedSince.test.ts
  packages/utils/date/getElapsedSince/getElapsedSince.ts
  packages/utils/date/getElapsedSince/index.ts
  packages/utils/date/index.ts
  packages/utils/index.ts
Labels: feature

#9 [refactor] Improve test coverage & Change scripts
  .gitignore
  .husky/pre-commit
  dist/hooks/index.d.ts
  dist/hooks/index.js
  dist/hooks/useDebounce/useDebounce.d.ts
  dist/hooks/useDebounce/useDebounce.js
  dist/hooks/useDebounce/useDebounce.test.d.ts
  dist/hooks/useDebounce/useDebounce.test.js
  dist/hooks/useFunnel/useFunnel.d.ts
  dist/hooks/useFunnel/useFunnel.js
  dist/hooks/useFunnel/useFunnel.test.d.ts
  dist/hooks/useFunnel/useFunnel.test.js
  dist/hooks/useImageInput/useImageInput.d.ts
  dist/hooks/useImageInput/useImageInput.js
  dist/hooks/useImageInput/useImageInput.test.d.ts
  dist/hooks/useImageInput/useImageInput.test.js
  dist/hooks/useText/useText.d.ts
  dist/hooks/useText/useText.js
  dist/hooks/useText/useText.test.d.ts
  dist/hooks/useText/useText.test.js
  dist/index.d.ts
  dist/index.js
  dist/utils/textValidators/index.d.ts
  dist/utils/textValidators/index.js
  dist/utils/textValidators/types.d.ts
  dist/utils/textValidators/types.js
  dist/utils/textValidators/validateEmail/index.d.ts
  dist/utils/textValidators/validateEmail/index.js
  dist/utils/textValidators/validateEmail/validateEmail.d.ts
  dist/utils/textValidators/validateEmail/validateEmail.js
  dist/utils/textValidators/validateEmail/validateEmail.test.d.ts
  dist/utils/textValidators/validateEmail/validateEmail.test.js
  dist/utils/textValidators/validateNickname/index.d.ts
  dist/utils/textValidators/validateNickname/index.js
  dist/utils/textValidators/validateNickname/validateNickname.d.ts
  dist/utils/textValidators/validateNickname/validateNickname.js
  dist/utils/textValidators/validateNickname/validateNickname.test.d.ts
  dist/utils/textValidators/validateNickname/validateNickname.test.js
  dist/utils/textValidators/validatePassword/index.d.ts
  dist/utils/textValidators/validatePassword/index.js
  dist/utils/textValidators/validatePassword/validatePassword.d.ts
  dist/utils/textValidators/validatePassword/validatePassword.js
  dist/utils/textValidators/validatePassword/validatePassword.test.d.ts
  dist/utils/textValidators/validatePassword/validatePassword.test.js
  package-lock.json
  package.json
  packages/hooks/useDebounce/useDebounce.test.tsx
  packages/hooks/useText/useText.tsx
  tsconfig.json
Labels: refactor

#11 [feat] Add formatUnit Util Function
  packages/utils/formatUnit/formatUnit.test.ts
  packages/utils/formatUnit/formatUnit.ts
  packages/utils/index.ts
Labels: feature

#13 [fix] Reset useText error after valid input and add test cases
  package-lock.json
  packages/hooks/useText/useText.test.ts
  packages/hooks/useText/useText.tsx
  tsconfig.json
Labels: bug
